version: "3.9"
services:
  ap:
    build:
      context: .docker/ap
      args:
        USER: ${USER}
        UID: 1000
        GROUP: ${USER}
        GID: 1000
        # RUBY_VERSION: 3.0.2
        # NODE_VERSION: 16.6.2
        # BUNDLER_VERSION: 2.2.25
        # RAILS_VERSION: 6.1.4
    # entrypoint: []
    # command: tail -f
    ports:
      - "3000:3000"
    # environment:
    #   RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    # volumes:
    #   - .:/app
